[build]
builder = "nixpacks"

[build.nixpacks]
nixPkgs = ["nodejs_20"]

[deploy]
startCommand = "npx prisma migrate deploy && npx prisma db seed && npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
